### ISSUE TITLE
Cannot find module './lodash-id.js

### ISSUE THREAD

**Issue by amaothree** [RealSpeaker/telegraf-session-local#45]
```
Error: Cannot find module './lodash-id.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:668:15)
    at Function.Module._load (internal/modules/cjs/loader.js:591:27)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at LocalSession._initDB (/home/amao/Git/R6statsTGbot/node_modules/telegraf-session-local/lib/session.js:274:19)
    at new LocalSession (/home/amao/Git/R6statsTGbot/node_modules/telegraf-session-local/lib/session.js:84:15)
    at Object.<anonymous> (/home/amao/Git/R6statsTGbot/index.js:19:10)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
```
The break line in my file is
```nodejs
bot.use((new LocalSession({ database: 'example_db.json' })).middleware())
```

I installed the lodash-id by npm but not solve the problem
 
Arch Linux + zsh
Webstorm

**Comment by TemaSM** [comment]
@amaothree may you please provide me zipped source of your bot (via [cloud](https://openload.cc/) or by Email: `github.tema@smirnov.one`), including `node_modules` folder, so I can reproduce issue? Because I cannot reproduce this issue in all of my environments, even at Travis CI.

**Comment by TemaSM** [comment]
@amaothree please reinstall by running:
`npm i -S telegraf-session-local@latest` or `npm i -S telegraf-session-local@1.0.2`

**Comment by amaothree** [comment]
It work, thanks a lot.
